language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  #- "3.6-dev" # 3.6 development branch
  #- "3.7-dev" # 3.7 development branch

install:
  - pip install pytest
  - pip install -e .[dev,test]

script: py.test

notifications:
  email: false